version: '3'
services:
  backend:
    build: .
    container_name: chillStream_auth_service
    ports:
      - "8081:8081"
    depends_on:
      - mongo
    volumes:
      - .:/app
    networks:
      - shared_network

  mongo:
    image: mongo:latest
    container_name: chillStream_auth_service_db
    ports:
      - "27018:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - shared_network

networks:
  shared_network:
    external: true

volumes:
  mongo_data:

