version: '3'
services:
  backend:
    build: .
    container_name: chillStream_auth_service
    ports:
      - "8081:8081"
    depends_on:
      - mongo
    volumes:
      - .:/app

  mongo:
    image: mongo:latest
    container_name: chillStream_auth_service_db
    ports:
      - "27018:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
